# Generated by Django 4.2 on 2023-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('custom_sharing', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commission',
            },
        ),
        migrations.CreateModel(
            name='CommissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PercentageMultiplierThreshold',
            fields=[
                ('thres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sales_amt', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('percent_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
                ('bonus_amt', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
            ],
            options={
                'db_table': 'percentage_multiplier_threshold',
            },
        ),
        migrations.CreateModel(
            name='ProductCommissionStructure',
            fields=[
                ('prod_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prod_com_rate', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('prod_com_amt', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
            options={
                'db_table': 'product_commission_structure',
            },
        ),
        migrations.CreateModel(
            name='ServiceCommissionStructure',
            fields=[
                ('service_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('service_com_category', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('service_com_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('service_com_amt', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
            ],
            options={
                'db_table': 'service_commission_structure',
            },
        ),
        migrations.CreateModel(
            name='VoucherCommissionStructure',
            fields=[
                ('voucher_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('voucher_com_rate', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('voucher_com_amt', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
            options={
                'db_table': 'voucher_commission_structure',
            },
        ),
        migrations.CreateModel(
            name='VariableCommissionSummary',
            fields=[
                ('var_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('adjusted_sales', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('com_amt', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.employee')),
                ('thres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissionsummary', to='core.percentagemultiplierthreshold')),
            ],
            options={
                'db_table': 'variable_commission_summary',
            },
        ),
        migrations.CreateModel(
            name='FixedCommissionSummary',
            fields=[
                ('fixed_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('com_amt', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.employee')),
            ],
            options={
                'db_table': 'fixed_commission_summary',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sales_amount', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('fixed_com_amount', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeecommission', to='core.commission')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeecommission', to='hrm.employee')),
            ],
            options={
                'db_table': 'employee_commission',
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='emp_share_percent',
            field=models.ManyToManyField(related_name='commission', through='core.EmployeeCommission', to='hrm.employee'),
        ),
    ]
