# Generated by Django 4.1.7 on 2023-04-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageMultiplierThreshold',
            fields=[
                ('thres_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sales_amt', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('percent_multiplier', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'percentage_multiplier_threshold',
            },
        ),
        migrations.CreateModel(
            name='ProductCommissionStructure',
            fields=[
                ('prod_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prod_com_rate', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
            options={
                'db_table': 'product_commission_structure',
            },
        ),
        migrations.CreateModel(
            name='ServicecCommissionStructure',
            fields=[
                ('service_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('service_com_category', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('service_com_rate', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
            options={
                'db_table': 'service_commission_structure',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('com_amt', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('com_datetime', models.DateTimeField(blank=True, null=True)),
                ('com_type', models.CharField(blank=True, max_length=50, null=True)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.employee')),
            ],
            options={
                'db_table': 'commission',
            },
        ),
    ]
