# Generated by Django 4.2 on 2023-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='sales',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='commission',
            name='sales_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission', to='pos.saleitem'),
        ),
        migrations.AlterUniqueTogether(
            name='variablecommissionsummary',
            unique_together={('emp', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='fixedcommissionsummary',
            unique_together={('emp', 'date')},
        ),
    ]
