# Generated by Django 4.1.7 on 2023-04-25 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_swift_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$', message='Invalid SWIFT code')])),
                ('bank_city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z\\s]+$', message='City name can only contain letters and spaces')])),
            ],
        ),
    ]
