# Generated by Django 4.2 on 2023-06-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommissionstructure',
            name='prod_com_amt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productcommissionstructure',
            name='prod_com_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercommissionstructure',
            name='voucher_com_amt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vouchercommissionstructure',
            name='voucher_com_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
    ]
