# Generated by Django 4.2 on 2023-05-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bankdatabase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankdatabase',
            table='bank_database',
        ),
    ]
