# Generated by Django 4.2 on 2023-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='app_name',
            field=models.CharField(choices=[('auth_core', 'Auth_Core'), ('core', 'Core'), ('crm', 'Crm'), ('hrm', 'Hrm'), ('inventory', 'Inventory'), ('pos', 'Pos'), ('marketing', 'Marketing'), ('store', 'Store'), ('storages', 'Storages'), ('rest_framework', 'Rest_Framework'), ('rest_framework_simplejwt', 'Rest_Framework_Simplejwt'), ('drf_spectacular', 'Drf_Spectacular')], max_length=255, unique=True),
        ),
    ]
