# Generated by Django 4.2 on 2023-05-07 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('inventory', '0001_initial'),
        ('hrm', '0004_alter_employeebankaccount_bank_acc_num_and_more'),
        ('core', '0004_alter_bankdatabase_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSharingDetail',
            fields=[
                ('com_sharing_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'commission_sharing_detail',
            },
        ),
        migrations.RenameModel(
            old_name='ServicecCommissionStructure',
            new_name='ServiceCommissionStructure',
        ),
        migrations.CreateModel(
            name='EmployeeCommissionSharingPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('com_sharing_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeecommissionsharingpercentage', to='core.commissionsharingdetail')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeecommissionsharingpercentage', to='hrm.employee')),
            ],
            options={
                'db_table': 'employee_commission_sharing_percentage',
            },
        ),
        migrations.CreateModel(
            name='CommissionSharingPlan',
            fields=[
                ('com_sharing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('com_sharing_name', models.CharField(max_length=150)),
                ('com_sharing_desc', models.TextField(blank=True, max_length=350, null=True)),
            ],
            options={
                'db_table': 'commission_sharing_plan',
                'unique_together': {('com_sharing_name',)},
            },
        ),
        migrations.AddField(
            model_name='commissionsharingdetail',
            name='com_sharing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissionsharingplan', to='core.commissionsharingplan'),
        ),
        migrations.AddField(
            model_name='commissionsharingdetail',
            name='emp_share_percent',
            field=models.ManyToManyField(related_name='commissionsharingdetail', through='core.EmployeeCommissionSharingPercentage', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='commissionsharingdetail',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissionsharingdetail', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='commissionsharingdetail',
            name='sales_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissionsharingdetail', to='pos.saleitem'),
        ),
    ]
