# Generated by Django 4.2 on 2023-05-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commissionsharingdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionsharingdetail',
            name='com_sharing',
        ),
        migrations.AddField(
            model_name='commissionsharingdetail',
            name='custom_percent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeecommissionsharingpercentage',
            name='share_percent',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.DeleteModel(
            name='CommissionSharingPlan',
        ),
    ]
