# Generated by Django 4.2 on 2023-06-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appconfig_app_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppConfig',
        ),
    ]
