# Generated by Django 4.2 on 2023-06-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_saleitem_cat_item_voucher_alter_sale_cust_and_more'),
        ('hrm', '0002_alter_employee_unique_together'),
        ('core', '0006_delete_appconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcommissionsummary',
            options={'verbose_name_plural': 'Fixed Commission Summaries'},
        ),
        migrations.AlterModelOptions(
            name='variablecommissionsummary',
            options={'verbose_name_plural': 'Variable Commission Summaries'},
        ),
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('sales_item',), ('sales',)},
        ),
        migrations.AlterUniqueTogether(
            name='employeecommission',
            unique_together={('com', 'emp')},
        ),
        migrations.AlterUniqueTogether(
            name='percentagemultiplierthreshold',
            unique_together={('sales_amt', 'percent_multiplier')},
        ),
    ]
