# Generated by Django 4.1.7 on 2023-04-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0003_role_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
