# Generated by Django 4.2 on 2023-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('crm', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=100, unique=True)),
                ('voucher_name', models.CharField(max_length=255)),
                ('voucher_desc', models.TextField(blank=True, null=True)),
                ('voucher_type', models.CharField(choices=[('discount', 'Discount Voucher'), ('gift', 'Gift Voucher'), ('promo', 'Promotional Voucher')], max_length=20)),
                ('voucher_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('voucher_discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voucher_start_date', models.DateField()),
                ('voucher_end_date', models.DateField()),
                ('voucher_created_date', models.DateTimeField(auto_now_add=True)),
                ('voucher_price', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('voucher_discount_percent', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('voucher_usage_limit', models.PositiveIntegerField()),
                ('voucher_user_limit', models.PositiveIntegerField()),
                ('voucher_conditions', models.TextField(blank=True)),
                ('voucher_redemption_count', models.PositiveIntegerField(default=0)),
                ('voucher_img', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('voucher_associated_custs', models.ManyToManyField(blank=True, to='crm.customer')),
                ('voucher_associated_products', models.ManyToManyField(blank=True, to='inventory.product')),
                ('voucher_associated_servicepkgs', models.ManyToManyField(blank=True, to='inventory.servicepackage')),
                ('voucher_associated_services', models.ManyToManyField(blank=True, to='inventory.service')),
                ('voucher_com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vouchercommissionstructure')),
            ],
            options={
                'db_table': 'voucher',
            },
        ),
    ]
