# Generated by Django 4.2 on 2023-06-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_genericvoucher_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucher',
            unique_together={('voucher_code',), ('voucher_name',)},
        ),
    ]
