# Generated by Django 4.2 on 2023-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_voucher_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_discount_value',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='voucher_img',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_discount_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_price',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_user_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
