# Generated by Django 4.2 on 2023-06-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_voucher_unique_together_remove_voucher_cust_and_more'),
        ('pos', '0004_rename_sales_total_amt_sale_gross_sales_amt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
