# Generated by Django 4.2 on 2023-06-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_alter_customer_unique_together_and_more'),
        ('core', '0007_alter_fixedcommissionsummary_options_and_more'),
        ('inventory', '0005_alter_inventorycategory_options_and_more'),
        ('marketing', '0007_delete_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVoucher',
            fields=[
                ('voucher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=100, unique=True)),
                ('voucher_name', models.CharField(max_length=255)),
                ('voucher_desc', models.TextField(blank=True, null=True)),
                ('voucher_type', models.CharField(choices=[('discount', 'Discount Voucher'), ('gift', 'Gift Voucher'), ('promo', 'Promotional Voucher')], max_length=20)),
                ('voucher_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('voucher_start_date', models.DateField(blank=True, null=True)),
                ('voucher_end_date', models.DateField(blank=True, null=True)),
                ('voucher_created_date', models.DateTimeField(auto_now_add=True)),
                ('voucher_price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('voucher_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('voucher_discount_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voucher_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_conditions', models.TextField(blank=True)),
                ('voucher_redemption_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cust', models.ManyToManyField(blank=True, to='crm.customer')),
                ('pkg', models.ManyToManyField(blank=True, related_name='itemvoucher', to='inventory.servicepackage')),
                ('prod', models.ManyToManyField(blank=True, related_name='itemvoucher', to='inventory.product')),
                ('service', models.ManyToManyField(blank=True, related_name='itemvoucher', to='inventory.service')),
                ('voucher_com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vouchercommissionstructure')),
            ],
            options={
                'db_table': 'item_voucher',
                'unique_together': {('voucher_name',), ('voucher_code',)},
            },
        ),
        migrations.CreateModel(
            name='GenericVoucher',
            fields=[
                ('voucher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=100, unique=True)),
                ('voucher_name', models.CharField(max_length=255)),
                ('voucher_desc', models.TextField(blank=True, null=True)),
                ('voucher_type', models.CharField(choices=[('discount', 'Discount Voucher'), ('gift', 'Gift Voucher'), ('promo', 'Promotional Voucher')], max_length=20)),
                ('voucher_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('voucher_start_date', models.DateField(blank=True, null=True)),
                ('voucher_end_date', models.DateField(blank=True, null=True)),
                ('voucher_created_date', models.DateTimeField(auto_now_add=True)),
                ('voucher_price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('voucher_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('voucher_discount_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voucher_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_conditions', models.TextField(blank=True)),
                ('voucher_redemption_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cust', models.ManyToManyField(blank=True, to='crm.customer')),
                ('voucher_com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vouchercommissionstructure')),
            ],
            options={
                'db_table': 'generic_voucher',
                'unique_together': {('voucher_name',), ('voucher_code',)},
            },
        ),
        migrations.CreateModel(
            name='CategoryVoucher',
            fields=[
                ('voucher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=100, unique=True)),
                ('voucher_name', models.CharField(max_length=255)),
                ('voucher_desc', models.TextField(blank=True, null=True)),
                ('voucher_type', models.CharField(choices=[('discount', 'Discount Voucher'), ('gift', 'Gift Voucher'), ('promo', 'Promotional Voucher')], max_length=20)),
                ('voucher_discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('voucher_start_date', models.DateField(blank=True, null=True)),
                ('voucher_end_date', models.DateField(blank=True, null=True)),
                ('voucher_created_date', models.DateTimeField(auto_now_add=True)),
                ('voucher_price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('voucher_discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('voucher_discount_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voucher_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('voucher_conditions', models.TextField(blank=True)),
                ('voucher_redemption_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categoryvoucher', to='inventory.inventorycategory')),
                ('cust', models.ManyToManyField(blank=True, to='crm.customer')),
                ('voucher_com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vouchercommissionstructure')),
            ],
            options={
                'db_table': 'category_voucher',
                'unique_together': {('voucher_name',), ('voucher_code',)},
            },
        ),
    ]
