# Generated by Django 4.2 on 2023-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvoucher',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genericvoucher',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemvoucher',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
