# Generated by Django 4.2 on 2023-07-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_alter_categoryvoucher_voucher_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryvoucher',
            old_name='voucher_price',
            new_name='voucher_sale_discount_percent',
        ),
        migrations.RenameField(
            model_name='genericvoucher',
            old_name='voucher_price',
            new_name='voucher_sale_discount_percent',
        ),
        migrations.RenameField(
            model_name='itemvoucher',
            old_name='voucher_price',
            new_name='voucher_sale_discount_percent',
        ),
        migrations.AddField(
            model_name='categoryvoucher',
            name='voucher_sale_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericvoucher',
            name='voucher_sale_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemvoucher',
            name='voucher_sale_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
            preserve_default=False,
        ),
    ]
