# Generated by Django 4.2 on 2023-07-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_rename_voucher_price_categoryvoucher_voucher_sale_discount_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryvoucher',
            old_name='voucher_discount_amt',
            new_name='voucher_use_discount_amt',
        ),
        migrations.RenameField(
            model_name='categoryvoucher',
            old_name='voucher_discount_percent',
            new_name='voucher_use_discount_percent',
        ),
        migrations.RenameField(
            model_name='genericvoucher',
            old_name='voucher_discount_amt',
            new_name='voucher_use_discount_amt',
        ),
        migrations.RenameField(
            model_name='genericvoucher',
            old_name='voucher_discount_percent',
            new_name='voucher_use_discount_percent',
        ),
        migrations.RenameField(
            model_name='itemvoucher',
            old_name='voucher_discount_amt',
            new_name='voucher_use_discount_amt',
        ),
        migrations.RenameField(
            model_name='itemvoucher',
            old_name='voucher_discount_percent',
            new_name='voucher_use_discount_percent',
        ),
    ]
