# Generated by Django 4.2 on 2023-07-03 08:42

from django.db import migrations, models
import marketing.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_rename_voucher_discount_amt_categoryvoucher_voucher_use_discount_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvoucher',
            name='voucher_code',
            field=models.CharField(blank=True, default=marketing.models.models.Voucher.voucher_code_generator, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genericvoucher',
            name='voucher_code',
            field=models.CharField(blank=True, default=marketing.models.models.Voucher.voucher_code_generator, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemvoucher',
            name='voucher_code',
            field=models.CharField(blank=True, default=marketing.models.models.Voucher.voucher_code_generator, max_length=100, null=True, unique=True),
        ),
    ]
