# Generated by Django 4.2 on 2023-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_alter_categoryvoucher_voucher_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvoucher',
            name='voucher_sale_discount_percent',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='genericvoucher',
            name='voucher_sale_discount_percent',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='itemvoucher',
            name='voucher_sale_discount_percent',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
        ),
    ]
