# Generated by Django 4.1.7 on 2023-04-04 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
