# Generated by Django 4.2 on 2023-06-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('emp_phone_num',), ('emp_nric',)},
        ),
    ]
