# Generated by Django 4.2 on 2023-06-24 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdatabase',
            name='bank_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bankdatabase',
            name='bank_swift_code',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$', message='Invalid SWIFT code')]),
        ),
    ]
