# Generated by Django 4.1.7 on 2023-03-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0002_alter_employeebankaccount_bank_acc_num_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="empy_phone_num",
            new_name="emp_phone_num",
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("emp_name", "emp_nric", "emp_phone_num")},
        ),
    ]
