# Generated by Django 4.2 on 2023-05-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_remove_employeebankaccount_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_nric',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_phone_num',
            field=models.CharField(max_length=50),
        ),
    ]
