# Generated by Django 4.1.7 on 2023-03-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrm", "0003_rename_empy_phone_num_employee_emp_phone_num_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeebankaccount",
            unique_together={("bank_acc_num", "emp")},
        ),
        migrations.AlterUniqueTogether(
            name="employeebenefitaccount",
            unique_together={("emp", "benefit_acc_num")},
        ),
    ]
