# Generated by Django 4.2 on 2023-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_employee_emp_nric_alter_employee_emp_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebankaccount',
            name='bank_acc_num',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employeebenefitaccount',
            name='benefit_acc_num',
            field=models.CharField(max_length=150),
        ),
    ]
