# Generated by Django 4.1.7 on 2023-04-10 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_employeebankaccount_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebenefitaccount',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employeebenefitaccount', to='hrm.employee'),
        ),
    ]
