# Generated by Django 4.1.7 on 2023-04-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_alter_employeebenefitaccount_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='emp_salary',
        ),
    ]
