# Generated by Django 4.1.7 on 2023-04-10 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0010_rename_salary_employee_emp_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_nric',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_phone_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='bank_acc_num',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='bank_acc_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='bank_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='employeebankaccount',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeebankaccount', to='hrm.employee'),
        ),
        migrations.AlterField(
            model_name='employeebenefitaccount',
            name='benefit_acc_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeebenefitaccount',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employeebenefitaccount', to='hrm.employee'),
        ),
    ]
