# Generated by Django 4.2 on 2023-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=300)),
                ('service_desc', models.TextField(blank=True, null=True)),
                ('service_category', models.CharField(blank=True, max_length=100, null=True)),
                ('service_price', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('service_discount_percent', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('service_img', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicecommissionstructure')),
            ],
            options={
                'db_table': 'service',
                'unique_together': {('service_name',)},
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('pkg_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pkg_name', models.CharField(max_length=300)),
                ('pkg_desc', models.TextField(blank=True, null=True)),
                ('pkg_category', models.CharField(max_length=100)),
                ('pkg_price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('pkg_img', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'service_package',
            },
        ),
        migrations.CreateModel(
            name='ServicePackageService',
            fields=[
                ('sps_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('num_treatments', models.IntegerField(default=1)),
                ('pkg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.servicepackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.service')),
            ],
            options={
                'db_table': 'service_package_service',
            },
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='service',
            field=models.ManyToManyField(related_name='servicepackage', through='inventory.ServicePackageService', to='inventory.service'),
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=300)),
                ('supplier_contact', models.BigIntegerField(blank=True, null=True)),
                ('supplier_addres', models.CharField(blank=True, max_length=1000, null=True)),
                ('supplier_acc_num', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_supplier',
                'unique_together': {('supplier_name', 'supplier_acc_num')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='servicepackage',
            unique_together={('pkg_name',)},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=300)),
                ('prod_desc', models.TextField(blank=True, null=True)),
                ('prod_category', models.CharField(max_length=100)),
                ('prod_cost', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('prod_price', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('prod_discount_percent', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('prod_qty', models.IntegerField()),
                ('prod_img', models.BinaryField(blank=True, null=True)),
                ('prod_sku', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('prod_barcode', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('prod_com', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productcommissionstructure')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productsupplier')),
            ],
            options={
                'db_table': 'product',
                'unique_together': {('prod_name',)},
            },
        ),
    ]
