# Generated by Django 4.2 on 2023-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='service',
            field=models.ManyToManyField(related_name='servicepackage', through='inventory.ServicePackageService', to='inventory.service'),
        ),
    ]
