# Generated by Django 4.1.7 on 2023-04-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCommissionStructure',
            fields=[
                ('prod_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('prod_com_rate', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
            options={
                'db_table': 'product_commission_structure',
            },
        ),
        migrations.CreateModel(
            name='ServicecCommissionStructure',
            fields=[
                ('service_com_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_com_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('service_com_rate', models.DecimalField(decimal_places=10, max_digits=1000)),
            ],
            options={
                'db_table': 'service_commission_structure',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prod_com',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventory.productcommissionstructure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='service_com',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='inventory.serviceccommissionstructure'),
            preserve_default=False,
        ),
    ]
