# Generated by Django 4.1.7 on 2023-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="prod_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="productssupplier",
            name="supplier_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="services",
            name="service_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
