# Generated by Django 4.2 on 2023-06-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productcommissionstructure_prod_com_amt_and_more'),
        ('inventory', '0002_inventorycategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.inventorycategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='core.productcommissionstructure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.productsupplier'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service', to='core.servicecommissionstructure'),
        ),
        migrations.AlterField(
            model_name='servicepackageservice',
            name='pkg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicepackageservice', to='inventory.servicepackage'),
        ),
        migrations.AlterField(
            model_name='servicepackageservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicepackageservice', to='inventory.service'),
        ),
    ]
