# Generated by Django 4.1.7 on 2023-03-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_products_prod_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productssupplier",
            name="supplier_acc_num",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
