# Generated by Django 4.2 on 2023-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_servicepackage_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='pkg_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='pkg_price',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
    ]
