# Generated by Django 4.2 on 2023-06-23 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_prod_category_alter_product_prod_com_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycategory',
            name='cat_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('servicepackage', 'Service Package')], max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='inventory.inventorycategory'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='pkg_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicepackage', to='inventory.inventorycategory'),
        ),
    ]
