# Generated by Django 4.1.7 on 2023-03-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_productssupplier_supplier_acc_num"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="products",
            unique_together={("prod_id", "prod_name", "supplier")},
        ),
        migrations.AlterUniqueTogether(
            name="productssupplier",
            unique_together={("supplier_name", "supplier_acc_num")},
        ),
        migrations.AlterUniqueTogether(
            name="services",
            unique_together={("service_name",)},
        ),
    ]
