# Generated by Django 4.1.7 on 2023-03-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_products_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="products",
            unique_together={("prod_name",)},
        ),
    ]
