# Generated by Django 4.2 on 2023-07-27 10:59

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='inventory/products'),
        ),
    ]
