# Generated by Django 4.2 on 2023-07-28 18:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_product_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_img',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='inventory/products'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='pkg_img',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='inventory/products'),
        ),
    ]
