# Generated by Django 4.2 on 2023-08-04 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productsize_rename_cat_id_inventorycategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.productbrand'),
            preserve_default=False,
        ),
    ]
