# Generated by Django 4.2 on 2023-08-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_prod_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsupplier',
            old_name='supplier_acc_num',
            new_name='acc_num',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='supplier_addres',
            new_name='addres',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='supplier_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='supplier_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='supplier_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('name', 'acc_num')},
        ),
    ]
