# Generated by Django 4.2 on 2023-08-04 20:46

from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rename_supplier_acc_num_productsupplier_acc_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_sku',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('value', 'unit')},
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'product_variant',
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='prod_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.productvariant'),
        ),
    ]
