# Generated by Django 4.2 on 2023-08-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productbrand_sku_part_productsize_sku_part_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('prod_barcode',), ('prod_sku',), ('prod_name', 'prod_category', 'prod_variant', 'prod_size', 'prod_weight')},
        ),
    ]
