# Generated by Django 4.2 on 2023-08-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_product_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSize',
            new_name='ProductUnitSize',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prod_size',
            new_name='prod_unit_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_sku',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='productunitsize',
            table='product_unit_size',
        ),
        migrations.CreateModel(
            name='ProductPackageSize',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('unit', models.CharField(max_length=25)),
                ('sku_part', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product_package_size',
                'unique_together': {('qty', 'unit')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('prod_barcode',), ('prod_sku',)},
        ),
        migrations.AddField(
            model_name='product',
            name='prod_package_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='inventory.productpackagesize'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('prod_barcode',), ('prod_name', 'prod_category', 'prod_variant', 'prod_unit_size', 'prod_package_size', 'prod_weight'), ('prod_sku',)},
        ),
    ]
