# Generated by Django 4.2 on 2023-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_productsize_productunitsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='sku_part',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_barcode',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_sku',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productbrand',
            unique_together={('name',), ('sku_part',)},
        ),
        migrations.AlterUniqueTogether(
            name='productpackagesize',
            unique_together={('qty', 'unit'), ('sku_part',)},
        ),
        migrations.AlterUniqueTogether(
            name='productunitsize',
            unique_together={('value', 'unit'), ('sku_part',)},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('name',), ('sku_part',)},
        ),
        migrations.AlterUniqueTogether(
            name='productweight',
            unique_together={('value', 'unit'), ('sku_part',)},
        ),
    ]
