# Generated by Django 4.2 on 2023-08-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventorycategory_sku_part_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('sku_part',), ('name',)},
        ),
    ]
