# Generated by Django 4.2 on 2023-08-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_product_prod_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('prod_barcode',), ('prod_name', 'prod_category', 'prod_variant', 'prod_unit_size', 'prod_package_size', 'prod_weight')},
        ),
    ]
