# Generated by Django 4.2 on 2023-08-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
