# Generated by Django 4.2 on 2023-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(choices=[('auth_core', 'auth_core'), ('core', 'core'), ('crm', 'crm'), ('hrm', 'hrm'), ('inventory', 'inventory'), ('pos', 'pos'), ('marketing', 'marketing'), ('store', 'store'), ('config', 'config'), ('storages', 'storages')], max_length=255, unique=True)),
                ('config_key', models.CharField(max_length=255)),
                ('config_value', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'App Configurations',
                'db_table': 'app_config',
            },
        ),
    ]
