# Generated by Django 4.2 on 2023-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('crm', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSubscription',
            fields=[
                ('pkg_sub_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paid_amt', models.DecimalField(decimal_places=10, default=0, max_digits=1000)),
                ('remaining_balance', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('fully_paid', models.BooleanField(default=False)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscription', to='crm.customer')),
                ('pkg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscription', to='inventory.servicepackage')),
            ],
            options={
                'db_table': 'package_subscription',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sales_datetime', models.DateTimeField(auto_now_add=True)),
                ('sales_total_amt', models.DecimalField(decimal_places=10, max_digits=1000)),
                ('sales_payment_type', models.CharField(max_length=100)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='crm.customer')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('sales_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_item_qty', models.IntegerField(blank=True, null=True)),
                ('sales_item_price', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('pkg_sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='pos.packagesubscription')),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='inventory.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='pos.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='inventory.service')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='marketing.voucher')),
            ],
            options={
                'db_table': 'sale_item',
            },
        ),
        migrations.CreateModel(
            name='PackageSubscriptionService',
            fields=[
                ('pkg_sub_service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('treatment_left', models.IntegerField()),
                ('pkg_sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscriptionservice', to='pos.packagesubscription')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscriptionservice', to='inventory.service')),
            ],
            options={
                'db_table': 'package_subscription_service',
            },
        ),
        migrations.AddField(
            model_name='packagesubscription',
            name='service',
            field=models.ManyToManyField(related_name='packagesubscription', through='pos.PackageSubscriptionService', to='inventory.service'),
        ),
    ]
