# Generated by Django 4.1.7 on 2023-03-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("sales_id", models.IntegerField(primary_key=True, serialize=False)),
                ("sales_date", models.DateField()),
                (
                    "sales_total_amt",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=1000, null=True
                    ),
                ),
                (
                    "sales_payment_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "cust",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "sales",
            },
        ),
        migrations.CreateModel(
            name="SalesItem",
            fields=[
                (
                    "sales_item_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "sale_item_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sales_item_qty", models.IntegerField(blank=True, null=True)),
                (
                    "sales_item_price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=1000, null=True
                    ),
                ),
                (
                    "prod",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.products",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pos.sales"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.services",
                    ),
                ),
            ],
            options={
                "db_table": "sales_item",
                "unique_together": {("sales_item_id", "service", "prod")},
            },
        ),
    ]
