# Generated by Django 4.1.7 on 2023-04-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sales_date', models.DateField()),
                ('sales_total_amt', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('sales_payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
            ],
            options={
                'db_table': 'sale',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('sales_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sale_item_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sales_item_qty', models.IntegerField(blank=True, null=True)),
                ('sales_item_price', models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True)),
                ('prod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.service')),
            ],
            options={
                'db_table': 'sale_item',
            },
        ),
    ]
