# Generated by Django 4.2 on 2023-05-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_treatment_cust_alter_treatment_emp'),
        ('inventory', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscription',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscription', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='packagesubscription',
            name='pkg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscription', to='inventory.servicepackage'),
        ),
        migrations.AlterField(
            model_name='packagesubscriptionservice',
            name='pkg_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscriptionservice', to='pos.packagesubscription'),
        ),
        migrations.AlterField(
            model_name='packagesubscriptionservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packagesubscriptionservice', to='inventory.service'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='pkg_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='pos.packagesubscription'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='prod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='pos.sale'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem', to='inventory.service'),
        ),
    ]
