# Generated by Django 4.1.7 on 2023-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="sales_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="sales_item_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
