# Generated by Django 4.2 on 2023-06-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_genericvoucher_and_more'),
        ('crm', '0002_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cat_item_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem_use', to='marketing.voucher'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='saleitem_buy', to='marketing.voucher'),
        ),
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucherusage', to='pos.sale')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucherusage', to='marketing.voucher')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='gen_voucher_used',
            field=models.ManyToManyField(related_name='sale', through='pos.VoucherUsage', to='marketing.voucher'),
        ),
    ]
