# Generated by Django 4.2 on 2023-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_packagesubscription_cust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_payment_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_total_amt',
            field=models.DecimalField(decimal_places=10, max_digits=1000),
        ),
    ]
