# Generated by Django 4.2 on 2023-06-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_voucher_unique_together'),
        ('inventory', '0005_alter_inventorycategory_options_and_more'),
        ('pos', '0002_saleitem_cat_item_voucher_alter_sale_cust_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagesubscriptionservice',
            unique_together={('pkg_sub', 'service')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherusage',
            unique_together={('voucher', 'sales')},
        ),
        migrations.AlterModelTable(
            name='voucherusage',
            table='voucher_usage',
        ),
    ]
