# Generated by Django 4.1.7 on 2023-03-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_alter_sales_sales_id_alter_salesitem_sales_item_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salesitem",
            unique_together=set(),
        ),
    ]
