# Generated by Django 4.2 on 2023-05-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_sale_sales_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagesubscription',
            name='payment_datetime',
        ),
    ]
