# Generated by Django 4.2 on 2023-06-26 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pos', '0003_alter_packagesubscriptionservice_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sales_total_amt',
            new_name='gross_sales_amt',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sales_item_price',
            new_name='gross_sales_item_price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='gen_voucher_used',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='cat_item_voucher',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='voucher',
        ),
        migrations.AddField(
            model_name='sale',
            name='net_sales_amt',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_sales_item_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voucher_sale_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voucher_sale_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'in': []}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleitem_sale', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voucher_use_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='voucher_use_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'in': []}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleitem_use', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='VoucherUsage',
        ),
    ]
