# Generated by Django 4.2 on 2023-06-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_initial'),
        ('pos', '0004_rename_sales_total_amt_sale_gross_sales_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucherusage', to='pos.sale')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucherusage', to='marketing.genericvoucher')),
            ],
            options={
                'db_table': 'voucher_usage',
                'unique_together': {('voucher', 'sales')},
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='gen_voucher_used',
            field=models.ManyToManyField(related_name='sale', through='pos.VoucherUsage', to='marketing.genericvoucher'),
        ),
    ]
