# Generated by Django 4.2 on 2023-05-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_treatment_cust_alter_treatment_emp'),
        ('pos', '0005_packagesubscription_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='crm.customer'),
        ),
    ]
