# Generated by Django 4.2 on 2023-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_alter_saleitem_voucher_sale_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='gross_sales_amt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='net_sales_amt',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
    ]
