# Generated by Django 4.2 on 2023-06-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pos', '0007_alter_sale_gross_sales_amt_alter_sale_net_sales_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='voucher_sale_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['itemvoucher', 'categoryvoucher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleitem_sale', to='contenttypes.contenttype'),
        ),
    ]
