# Generated by Django 4.2 on 2023-06-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_saleitem_voucher_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='gross_sales_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='net_sales_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='gross_sales_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='net_sales_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
