# Generated by Django 4.2 on 2023-06-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_alter_saleitem_voucher_use_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesubscription',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=1000, null=True),
        ),
    ]
