# Generated by Django 4.2 on 2023-07-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_packagesubscription_remaining_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='gross_sales_item_price',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='net_sales_item_price',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gross_sales_item_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='gross_sales_item_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_sales_item_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_sales_item_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
            preserve_default=False,
        ),
    ]
