# Generated by Django 4.2 on 2023-07-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_remove_saleitem_gross_sales_item_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sales_payment_type',
            new_name='sales_payment_method',
        ),
    ]
