# Generated by Django 4.1.7 on 2023-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("cust_id", models.IntegerField(primary_key=True, serialize=False)),
                ("cust_name", models.CharField(max_length=150)),
                ("cust_phone_num", models.BigIntegerField(blank=True, null=True)),
                (
                    "cust_address",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("cust_dob", models.DateField(blank=True, null=True)),
                ("cust_email", models.CharField(blank=True, max_length=300, null=True)),
                ("cust_nric", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "customer",
                "unique_together": {("cust_id", "cust_phone_num", "cust_nric")},
            },
        ),
    ]
