# Generated by Django 4.1.7 on 2023-04-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=150)),
                ('cust_phone_num', models.BigIntegerField(blank=True, null=True)),
                ('cust_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('cust_dob', models.DateField(blank=True, null=True)),
                ('cust_email', models.CharField(blank=True, max_length=300, null=True)),
                ('cust_nric', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateTimeField()),
                ('treatment_notes', models.TextField(blank=True)),
                ('treatment_img', models.ImageField(upload_to='')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrm.employee')),
            ],
            options={
                'db_table': 'treatment',
            },
        ),
    ]
