# Generated by Django 4.2 on 2023-06-22 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=150)),
                ('cust_phone_num', models.BigIntegerField()),
                ('cust_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('cust_dob', models.DateField(blank=True, null=True)),
                ('cust_email', models.CharField(blank=True, max_length=300, null=True)),
                ('cust_nric', models.BigIntegerField()),
                ('cust_occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('cust_source', models.CharField(blank=True, choices=[('advertisement', 'Advertisement'), ('referral', 'Referral'), ('online_search', 'Online Search'), ('social_media', 'Social Media'), ('word_of_mouth', 'Word of Mouth'), ('event', 'Event'), ('newspaper', 'Newspaper'), ('television', 'Television'), ('radio', 'Radio'), ('email_marketing', 'Email Marketing'), ('direct_mail', 'Direct Mail'), ('other', 'Other')], max_length=30, null=True)),
                ('cust_med_hist', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_date', models.DateTimeField()),
                ('treatment_notes', models.TextField(blank=True)),
                ('treatment_img', models.ImageField(upload_to='')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment', to='crm.customer')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment', to='hrm.employee')),
            ],
            options={
                'db_table': 'treatment',
            },
        ),
    ]
