# Generated by Django 4.1.7 on 2023-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cust_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
