# Generated by Django 4.1.7 on 2023-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_customer_cust_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="cust_nric",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
