# Generated by Django 4.2 on 2023-07-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_rename_gen_voucher_used_sale_gen_voucher_use'),
        ('crm', '0003_alter_customer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='pkg_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment', to='pos.packagesubscription'),
        ),
    ]
