# Generated by Django 4.1.7 on 2023-03-27 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_customer_cust_nric"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={
                ("cust_id", "cust_phone_num", "cust_nric", "cust_name", "cust_email")
            },
        ),
    ]
