# Generated by Django 4.2 on 2023-07-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_treatment_pkg_sub'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treatment',
        ),
    ]
