# Generated by Django 4.2 on 2023-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treatment_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
